feature/artif-city-map
MTES-MCT/sparte pull request #106
Opened 2023-12-20 13:21 UTC by smdsgn

2024-01-16 15:15 UTC, alexisig requested changes
Il y a plusieurs problèmes de structure dans les différentes classes qui composent le code relatif à MapLibre, notamment en terme de couplage des classes les unes avec les autres (child -> parent) et avec window / des élèments du dom.

A mon avis le code gagnerait à utiliser de l'[injection de dépendances](https://www.softfluent.fr/blog/injection-de-dependances-a-quoi-ca-sert/) et des [fonctions pures](https://en.wikipedia.org/wiki/Pure_function), pour la lisibilité mais aussi pour éviter les bugs des effets de bord.

Je pense qu'une partie des problèmes disparaitra avec React, mais que le code qui restera ou qui cohabitera avec React le temps de la migration pourra nous poser problème.

Je comprends que la plupart du code a juste été déplacé + modifié par le linter, donc si c'est pas faisable sur cette PR pas de soucis, mais si les points te semblent justifiés peut-être on peut en créer des tickets et les faire plus tard ?

Le reste des retours c'est principalement de la syntaxe (forEach au lieu de map ou inversement) / des choses qui peuvent être simplifiées.

2024-01-18 12:51 UTC, Swannbm reviewed
J'ai relu, mais je n'ai rien à me mettre sous la dent côté python.

2024-01-18 12:53 UTC, Swannbm approved these changes
C'est bon pour map.py
Je ne revois pas le js.

2024-01-22 09:57 UTC, alexisig approved these changes

2024-01-22 13:48 UTC, merged