Fix local report V2
MTES-MCT/sparte pull request #358
Opened 2024-05-27 08:56 UTC by smdsgn

2024-05-28 11:58 UTC, alexisig requested changes

2024-05-28 11:58 UTC, alexisig commented on project/charts/NetArtifComparaisonChart.py
> +            "legend": {"navigation": {"enabled": False}},
Ici il faudrait utiliser la variable `LEGEND_NAVIGATION_EXPORT` (de `project/charts/constants.py`)

2024-05-28 11:58 UTC, alexisig commented on project/charts/NetArtifComparaisonChart.py
> +            },
top 👍

2024-05-28 11:58 UTC, alexisig commented on diagnostic_word/renderers.py
> +                table_comparison = chart_comparison_series
je fais une PR sur la PR pour te proposer autre chose

2024-05-28 12:17 UTC, smdsgn commented on project/charts/NetArtifComparaisonChart.py
> +            "legend": {"navigation": {"enabled": False}},
Oui je ne l'avais pas vue cette variable, c'est déjà dans mon prochain commit.

2024-05-29 08:26 UTC, alexisig approved these changes

2024-05-29 13:47 UTC, merged