Carte disponibilité de l'OCS GE sur Mon Diag Artif
MTES-MCT/sparte pull request #438
Opened 2024-06-13 15:53 UTC by smdsgn

2024-06-18 16:32 UTC, alexisig requested changes
Top que t'aies réussi à faire tout ça en react 👌
quelques retours sur la forme et un retour sur un potentiel de bug (`updateGeoJSONProperties`) mais sinon c'est top !
On fait la recette sur l'app review du coup ?

2024-06-18 16:32 UTC, alexisig commented on assets/scripts/components/HighchartsMapOcsge.tsx
> +      }),
A mon avis ce serait intéressant de ne pas avoir cette condition ici. Si le département n'est pas trouvé, ça failerait silencieusement. A minima je pense qu'un `console.warn` indiquant quel département est manquant serait pas mal, mais idéalement j'ajouterai plutôt un test pour s'assurer que les départements en BDD et dans ce fichier matchent. On pourrait sortir les départements en fixture pour faire ce test d'ailleurs

2024-06-18 16:32 UTC, alexisig commented on assets/scripts/components/HighchartsMapOcsge.tsx
> +import topology from '../../geojson/departements-1000m-dept-simpl-displaced-vertical.geojson';
Je pense que ce fichier devrait être chargé indépendamment du bundle pour ne pas l'alourdir. Je vois 621ko sur l'app review contre 293ko en prod

2024-06-18 16:32 UTC, alexisig commented on assets/scripts/components/HighchartsMapOcsge.tsx
> +  ocsge_millesimes: string | null;
```suggestion
  id: number;
  source_id: string;
  name: string;
  region_id: number;
  is_artif_ready: boolean
  ocsge_millesimes: number[] | null;
```

2024-06-18 16:32 UTC, alexisig commented on assets/scripts/components/HighchartsMapOcsge.tsx
> +  }, [data]);
faudrait garder ce hook en haut du component, en sortant la fonction `updateGeoJSONProperties`  
https://react.dev/reference/rules/rules-of-hooks

2024-06-18 16:32 UTC, alexisig commented on assets/scripts/services/api.js
> +})
est-ce que c'était pas possible d'utiliser le même `createApi`et d'y ajouter un endpoint ?

2024-06-18 22:18 UTC, smdsgn commented on assets/scripts/services/api.js
> +})
Je pense que c'est justifié comme on a deux baseUrl différentes et potentiellement des conf différentes aussi. Maintenant on peut utiliser un seul createApi sans baseUrl mais avec des routes complètes en attendant de voir si on en a réellement besoin dans le futur. J'ai pas plus d'avis que ça...

2024-06-18 22:23 UTC, smdsgn commented on assets/scripts/components/HighchartsMapOcsge.tsx
> +      }),
On est pas sur une fonctionnalité critique, ça reste de l'affichage. C'est overkill je pense de mettre un test ici, mais pourquoi pas un warm.

2024-06-19 12:28 UTC, alexisig commented on assets/scripts/services/api.js
> +})
j'avais crée la base `/api/v2` pour y mettre les endpoints spécifiques à react (et ne pas toucher aux endpoints existant), mais j'y tiens pas particulièrement. Je pense que tu peux supprimer la conf de ces endpoints si on s'en sert pas et n'avoir qu'un seul `createApi` côté front du coup. Cad :
- `project/urlsv2.py`
- `project/api_views_v2.py`

2024-06-19 21:29 UTC, alexisig approved these changes
LGTM

2024-06-19 21:50 UTC, merged