Création de l'onglet imperméabilisation
MTES-MCT/sparte pull request #493
Opened 2024-07-02 07:55 UTC by smdsgn

2024-07-04 12:34 UTC, alexisig requested changes
LGTM, quelques modifs d'éléments restés similaires à l'artif mis en suggestion

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +                        <p class="fr-text--sm">En hectare (Ha).</p>
```suggestion
                        <p class="fr-text--sm">En hectare (ha).</p>
```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +                        <p class="fr-text--sm">En hectare (Ha).</p>
```suggestion
                        <p class="fr-text--sm">En hectare (ha).</p>
```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +                        <p class="fr-text--sm">Imperméabilisation sur la période - Désimperméabilisation sur la période.</p>
```suggestion
                        <p class="fr-text--sm">Imperméabilisation nette = Imperméabilisation sur la période - Désimperméabilisation sur la période.</p>
```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +                        <p class="fr-text--sm">Il y a eu 7.5 ha de nouvelles Zones non bâties représentant 10% de la surface de toutes les nouvelles surfaces artificialisées et 2 ha d'anciennes Zones
```suggestion
                        <p class="fr-text--sm">Il y a eu 7.5 ha de nouvelles Zones non bâties représentant 10% de la surface de toutes les nouvelles surfaces imperméabilisées et 2 ha d'anciennes Zones non bâties désimperméabilisée représentant 16% de la surface de toutes les zones désimperméabilisées.</p>
```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +                <p class="fr-text--sm">Vous pouvez analyser la répartition des surfaces artificialisées sur la période en pourcentage avec le camembert, ou en volume au dernier millésime avec l'histo
```suggestion
                <p class="fr-text--sm">Exemple de lecture: 8% des nouvelles surfaces imperméabilisées le sont pour des Zones bâties.</p>
                <p class="fr-text--sm">Vous pouvez analyser la répartition des surfaces imperméabilisées sur la période en pourcentage avec le camembert, ou en volume au dernier millésime avec l'histogramme.</p>
```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +                <p class="fr-text--sm">Vous pouvez analyser la répartition des surfaces artificialisées sur la période en pourcentage avec le camembert, ou en volume au dernier millésime avec l'histo
```suggestion
                <p class="fr-text--sm">Vous pouvez analyser la répartition des surfaces imperméabilisées sur la période en pourcentage avec le camembert, ou en volume au dernier millésime avec l'histogramme.</p>
```

2024-07-04 12:34 UTC, alexisig commented on public_data/templates/public_data/partials/imper_nette_table.html
> +</div>
```suggestion
</div>

```

2024-07-04 12:34 UTC, alexisig commented on public_data/templates/public_data/partials/imper_sol_table.html
> +</div>
```suggestion
</div>

```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +            <h3>Grandes familles d'usages du sol des surfaces artificialisées</h3>
```suggestion
            <h3>Grandes familles d'usages du sol des surfaces imperméabilisées</h3>
```

2024-07-04 12:34 UTC, alexisig commented on project/templates/project/report_imper.html
> +            <h3>Grandes familles de couverture des sols des surfaces artificialisées</h3>
```suggestion
            <h3>Familles de couverture des sols des surfaces imperméabilisées</h3>
```
J'ai aussi remplacé `grande famille` par `famille` ici parce que les deux couvertures sont de la même grande famille

2024-07-04 14:32 UTC, merged

2024-07-12 09:01 UTC, Phil-Loriot commented
OK pour moi