Pre-commit: configuration, fix global du format et documentation
MTES-MCT/sparte pull request #55
Opened 2023-10-24 13:57 UTC by alexisig

- Ajout des étapes d'installation de pre-commit dans le readme
- Ajout de flake8 au pre-commit
- Fix global du format (automatique)
- Bump de version de black

Tous les changements automatiques obtenus via la commande `pre-commit run --all-file` ont été vérifiés.

2023-10-25 19:33 UTC, Swannbm requested changes

2023-10-25 19:33 UTC, Swannbm commented on README.md
> +- Depuis l'environement pipenv, installer la configuration pre-commit sur votre dépot git local : `pre-commit install`
Le terme "shell" me semble plus précis qu'environnement.

2023-10-25 19:33 UTC, Swannbm commented on public_data/urls.py
> -    path("grid", grid_views, name="grid")
il faut ajouter une virgule à la fin de la ligne du dernier item pour forcer black a mettre un item par ligne. Dans le fichier urls.py ça me semble une convention plutôt pertinente (une ligne = une url).

2023-10-25 19:33 UTC, Swannbm commented on .pre-commit-config.yaml
>  # See https://pre-commit.com for more information
Pourrais-tu ajouter isort aussi stp ?

2023-10-25 19:33 UTC, Swannbm commented on .pre-commit-config.yaml
>      - id: black
Est-ce que black doit s'exécuter sur les fichiers javascript ? J'ai vu qu'il remplaçait les ' par des " et je ne sais pas si c'est vraiment une convention dans le monde js... Qu'en penses-tu ?

2023-10-25 19:33 UTC, Swannbm commented on .pre-commit-config.yaml
>      - id: black
D'ailleurs, peut-être ajouter un linter dédié aux fichiers js ?

2023-10-26 10:37 UTC, alexisig commented on .pre-commit-config.yaml
>      - id: black
Bien vu, la convention en JS c'est d'utiliser les simple quote par défaut, et les double quand on veut mettre des simples quotes dans le string.

2023-10-26 10:39 UTC, alexisig commented on .pre-commit-config.yaml
>      - id: black
Oui ça me semble bien de séparer les deux. Est-ce que ça te va de le faire une autre MR dans un second temps et d'ignorer les fichiers front pour le moment ?

2023-10-27 09:52 UTC, Swannbm commented on .pre-commit-config.yaml
>      - id: black
Oui, très bien !

2023-10-27 09:52 UTC, Swannbm commented on .pre-commit-config.yaml
>  # See https://pre-commit.com for more information
Tu peux résolve quand c'est fait.

2023-10-27 09:55 UTC, smdsgn submitted a review, later dismissed

2023-10-30 15:30 UTC, Swannbm approved these changes

2023-10-31 09:44 UTC, Swannbm approved these changes

2023-10-31 09:45 UTC, merged