Dashboard
MTES-MCT/sparte pull request #559
Opened 2024-08-02 14:04 UTC by smdsgn

2024-10-01 10:37 UTC, alexisig requested changes
Top tout ça !

Peu de choses à redire comme prévu, juste quelques points de docs :
- Les intentions ne sont pas toujours documentées et je vois pas mal de cas où elles ne sont pas toujours évidentes (j'ai mis des retours "intention" dans la PR)
- Le passage backend / frontend est parfois hardcodé. A mon avis il faudrait faire en sorte que le backend transmette ses infos au maximum, afin qu'un changement backend soit reflété dans le frontend et qu'on ait pas à faire les modifs à deux endroits. Je pense surtout aux urls et aux enums
- Les choix temporaires qui ont été faits pour livrer rapidement ne sont pas toujours identifiables. (j'ai mis des retours "temporaire" dans la PR)
- Concernant l'utilisation de `dangerouslySetInnerHTML :  est-ce que tu sais si un input utilisateur contenant de l'HTML, une fois render et escape par django, ne s'affiche pas comme HTML malgré tout une fois passé dans dangerouslySetInnerHTML ?

Dans l'ensemble je changerai pas grand chose, mais j'ajouterai pas mal de commentaires, notamment pour que je puisse comprendre pourquoi certaines choses ont été faites, et que je puisse participer au refactoring pour les choses que tu voudrais qu'on change à terme.

2024-10-01 10:37 UTC, alexisig commented on assets/scripts/hooks/usePageTitle.ts
> +};
url hardcodé

2024-10-01 10:37 UTC, alexisig commented on assets/scripts/services/api.ts
> +          url: '/public/search-land',
url hardcodé

2024-10-01 10:37 UTC, alexisig commented on assets/scripts/services/api.ts
> +      query: (id) => `/project/${id}/detail`,
url hardcodé

2024-10-01 10:37 UTC, alexisig commented on assets/scripts/services/api.ts
> +      query: () => '/public/departements/',
url hardcodé

2024-10-01 10:37 UTC, alexisig commented on assets/types/svg.d.ts
> +}
```suggestion
}

```

2024-10-01 10:37 UTC, alexisig commented on babel.config.js
> +};
```suggestion
};

```

2024-10-01 10:37 UTC, alexisig commented on config/middlewares.py
> +        return response
intention

2024-10-01 10:37 UTC, alexisig commented on highcharts/templates/highcharts/display_chart_data.html
> +    {{ json_options|safe }}
est-ce qu'on est certains qu'il ne peut pas y avoir d'input utilisateur ici ?

2024-10-01 10:37 UTC, alexisig commented on package.json
> +}
```suggestion
}

```

2024-10-01 10:37 UTC, alexisig commented on project/templates/project/layout/base.html
> +        </script>
temporaire ? passage en api ?

2024-10-01 10:37 UTC, alexisig commented on utils/views_mixins.py
> +        # Distinction pour les requêtes AJAX
intention

2024-10-01 10:37 UTC, alexisig commented on project/templates/project/pages/list.html
> +    }
temporaire ? intention ?

2024-10-02 15:26 UTC, smdsgn commented on highcharts/templates/highcharts/display_chart_data.html
> +    {{ json_options|safe }}
Je pense que oui.

2024-10-02 15:44 UTC, smdsgn commented on assets/scripts/components/layout/Footer.tsx
> +                                rel={item.target === "_blank" ? "noopener noreferrer" : undefined}
rel est un attribut non booléen, je dois bien le définir à undefined. Avec ta suggestion il sera a false.

2024-10-03 16:30 UTC, alexisig commented on assets/scripts/components/layout/Footer.tsx
> +                                rel={item.target === "_blank" ? "noopener noreferrer" : undefined}
S'il est à `false` l'attribut rel disparait (c'est aussi vrai pour `undefined` et `null`) : 
https://codesandbox.io/p/sandbox/naughty-diffie-lvhmcs?file=%2Fsrc%2Findex.js%3A7%2C1

2024-10-03 16:42 UTC, smdsgn commented on assets/scripts/components/layout/Footer.tsx
> +                                rel={item.target === "_blank" ? "noopener noreferrer" : undefined}
Ben non il ne disparait pas tu auras un rel à false et les attributs HTML ne doivent pas recevoir de valeur booléenne.

2024-10-03 16:44 UTC, smdsgn commented on assets/scripts/components/layout/Footer.tsx
> +                                rel={item.target === "_blank" ? "noopener noreferrer" : undefined}
<img width="472" alt="Capture d’écran 2024-10-03 à 18 43 50" src="https://github.com/user-attachments/assets/b2c482c7-c490-4050-94b1-ba61db9cf9fa">

2024-10-14 07:12 UTC, alexisig approved these changes
LGTM

2024-10-14 07:20 UTC, merged