Essone et Seine-et-Marne OCS GE + Refactor AutoloadMixin
MTES-MCT/sparte pull request #67
Opened 2023-10-31 10:33 UTC by alexisig

2023-11-01 10:27 UTC, Swannbm commented on project/models/create.py
> +from .project_base import Project
cf. l'autre PR :)

2023-11-01 11:01 UTC, Swannbm requested changes
Super, j'aime beaucoup l'ajout de sous fonction spécialisées pour découper load, l'augmentation des docstrings, etc.

La conséquence c'est que ça me donne envie d'aller plus loin et je t'ai mis plus de boulot, j'espère que ça ne te dérange pas !

2023-11-01 11:01 UTC, Swannbm commented on public_data/models/mixins.py
> -        clean_queryset=None,
Cela m'a donner de la souplesse à certains moment pour faire une reprise du chargement après crash. Il est possible que les options de LayerMapping rende cette option obsolète, mais c'est une idée à avoir en tête si on a des difficultés à charger certaines data : trouver un moyen pour reprendre là où ça a crashé plutôt que de devoir tout refaire :)

2023-11-06 09:19 UTC, alexisig commented on scripts/cmd.py
> +def mep_seine_et_marne(ctx):
renommer en load

2023-11-06 09:20 UTC, alexisig commented on scripts/cmd.py
> +def mep_essonne(ctx):
idem

2023-11-06 15:35 UTC, alexisig commented
@Swannbm prêt pour une nouvelle review 👍

2023-11-20 14:34 UTC, Swannbm approved these changes

2023-11-21 13:20 UTC, smdsgn approved these changes

2023-11-21 13:21 UTC, merged