Fix erreur d'import circulaire
MTES-MCT/sparte pull request #68
Opened 2023-10-31 11:05 UTC by alexisig

Résoud l'erreur:
```python
ImportError: cannot import name 'Project' from partially initialized module 'project.models' (most likely due to a circular import) (/app/project/models/__init__.py)
```

2023-10-31 13:15 UTC, Swannbm commented
Peux-tu m'indiquer quand l'erreur que tu rencontres se produit stp ?

2023-10-31 13:24 UTC, alexisig commented
> Peux-tu m'indiquer quand l'erreur que tu rencontres se produit stp ?

Ca me le fait au démarrage de Django depuis aujourd'hui

2023-11-01 10:24 UTC, Swannbm commented
Je viens d'enquêter. Le problème vient de la correction du fichier project.models.__init__ avec l'import à la fonction de création **avant** l'import du modèle Project ; j'avais déjà rencontré le soucis et fais la correction il y a longtemps (mais je n'avais pas mis de commentaire, my bad).

Sauf erreur, tu as injecté ce bug lors de la PR du pre-commit où tu as appliqué le isort partout, non ?

**Proposition de règle :**

Aux imports relatifs, je préfère les imports absolues qui apportent de la clareté quant à la provenance des imports. Avec notre base de code et la multiplicité des fichiers project.py (je sais, c'est ballot, ça me fait mal rien que de regarder) je pense qu'il est préférable de coller aux imports absolus autant que faire se peut. La seule dérogation serait : dans les fichiers __init__ on préfèrera les imports relatifs.

Si vous êtes OK et au vu de la règle proposé ci-dessus, je recommande plutôt de modifier le fichier init plutôt que de faire un import relatif ailleurs.

![image](https://github.com/MTES-MCT/sparte/assets/2237145/10c8c771-6cd1-4848-afe7-693e0b63e8f2)

Qu'en pensez-vous ?

Est-ce qu'on en profiterai pas pour mettre un fichier CODE_RULES.md à la racine du répo avec cette règle ?

2023-11-01 10:26 UTC, Swannbm requested changes
cf commentaire.

* [ ] garder un import absolue dans create.py
* [ ] modifier l'ordre des imports dans models/__init__.py, utiliser les annotations isort pour que ça reste compliant, ajouter un commentaire pour éviter qu'on reproduise ce bug une troisième fois :)
* [ ] créer un fichier CODE_RULES.md et l'initialiser avec la règle mis au jour lors de cette PR

2023-11-02 14:26 UTC, Swannbm approved these changes

2023-11-02 14:27 UTC, merged