Remplacer les graphiques de conso/surface par une treemap
MTES-MCT/sparte pull request #790
Opened 2024-12-06 16:09 UTC by smdsgn

2024-12-16 21:02 UTC, alexisig requested changes
Top ! J'ai laissé quelques suggestions sur le code. Pour la légende, je ne la trouve pas particulièrement utile (comme on a déjà toutes les infos dans le graph), tu en penses quoi ?

2024-12-16 21:02 UTC, alexisig commented on project/charts/consommation/AnnualConsoProportionalComparisonChart.py
>  class AnnualConsoProportionalComparisonChartExport(AnnualConsoProportionalComparisonChart):
Tu as pu tester le rendu sur l'export ?

2024-12-16 21:33 UTC, smdsgn commented on public_data/domain/consommation/entity/ConsommationStatistics.py
> +    per_mille_of_area: float
Je le passerais bien en pour cent comme évoqué en séminaire, c'est pas très parlant le pour mille je trouve.

2024-12-16 21:34 UTC, smdsgn commented on project/charts/consommation/AnnualConsoProportionalComparisonChart.py
>  class AnnualConsoProportionalComparisonChartExport(AnnualConsoProportionalComparisonChart):
Non et je ne l'ai pas intégré à l'export pour l'instant.

2024-12-16 22:18 UTC, alexisig commented on public_data/domain/consommation/entity/ConsommationStatistics.py
> +    per_mille_of_area: float
yes bonne idée

2024-12-16 22:21 UTC, alexisig commented on project/charts/consommation/AnnualConsoProportionalComparisonChart.py
>  class AnnualConsoProportionalComparisonChartExport(AnnualConsoProportionalComparisonChart):
`AnnualConsoProportionalComparisonChartExport` est déjà présent dans le rapport complet c'est pour ça que je demande

2024-12-16 22:21 UTC, alexisig commented on project/charts/consommation/AnnualConsoProportionalComparisonChart.py
>  class AnnualConsoProportionalComparisonChartExport(AnnualConsoProportionalComparisonChart):
[Diagnostic_de_Auch_2011_à_2022_issu_de_MonDiagnosticArtificialisation (1).docx](https://github.com/user-attachments/files/18157726/Diagnostic_de_Auch_2011_a_2022_issu_de_MonDiagnosticArtificialisation.1.docx)

2025-01-06 09:20 UTC, alexisig approved these changes

2025-01-06 09:44 UTC, merged