Masquer les EPCI étalés sur plusieurs departements
MTES-MCT/sparte pull request #82
Opened 2023-11-14 14:02 UTC by alexisig

Répond aux demandes des US:
- https://app.clickup.com/t/8693375m5
- https://app.clickup.com/t/8692y28dh

----

- Ajoute un status "ocsge_available" aux communes (boolean) -> calculé lors de l'éxécution de build_commune_daya
- Ajoute un attribut "ocsge_status" aux projets. 4 valeurs possible -> calculé dans une tâche asynchrone lors de la création du diagnostic
    - `COMPLETE_UNIFORM` : couverture en ocsge de toutes les communes du projet + communes dans un seul département
    - `COMPLETE_NOT_UNIFORM`: couverture en ocsge de toutes les communes du projet + communes dans plus de 1 département
    - `PARTIAL`: certaines communes couvertures en ocsge, mais pas toutes
    - `NO_DATA` : aucune commune couverture en ocsge
- Affiche le splash screen lors du changement de paramètre
- Affiche un message différent en fonction du status (ocsge_status.html)
- Améliore les fonctions de cleanup de load_ocsge en se basant sur un champ "Departement" au lieu d'une intersection spatiale

----

Pour déployer, lancer la commande `mep_ocsge_440 ` du fichier `scripts/cmd.py`

Le cas des projets sur plusieurs départements partageant les mêmes années de millésime sera traité dans une prochaine US: https://app.clickup.com/t/86938ux3q

2023-11-27 11:13 UTC, Swannbm commented
> Remplace la propriété `is_artif` de `Project` en 4 status distinct:
> 
>     * `complete`: tout le territoire est couvert par l'OCS GE -> Par exemple CA Grand Paris Sud Seine Essone Sénart, qui est totalement recouvert par l'OCS GE des départements Essonne et Seine-Et-Marne
> 
>     * `uniform`: tout le territoire est couvert par l'OCS GE, et la donnée provient d'un seul département (même millésime et recette). Par exemple CA Grand Auch Cœur de Gascogne
> 
>     * `partial`: au moins une des collectivités du territoire est couvert par l'OCS GE. Par exemple: CC d'Aire-sur-l'Adour
> 
>     * `empty`: pas de données OCS GE


* uniform: tout le territoire est couvert par l'OCS GE avec les mêmes millésimes
* complete: tout le territoire est couvert par l'OCS GE mais il y a des millésimes différents
* partial: au moins une des collectivités du territoire est couvert par l'OCS GE et au moins une commune ne l'est pas
* empty: pas de données OCS GE

2023-11-29 10:55 UTC, alexisig commented on public_data/migrations/0105_auto_20231122_0843.py
> +# Generated by Django 4.2.6 on 2023-11-22 08:43
Est-ce que la migration mineure proposée à la place te convient ? 
Elle dépend de l'exécution préalable de https://github.com/MTES-MCT/sparte/pull/88

2023-12-05 15:49 UTC, Swannbm requested changes

2023-12-05 15:49 UTC, Swannbm commented on project/models/project_base.py
> +        return self.OcsgeCoverageStatus.UNDEFINED
utiliser else voir juste retourner no_data à la fin sans condition.

2023-12-05 15:49 UTC, Swannbm commented on project/models/project_base.py
> -    def is_artif(self):
à conserver, mettre project.ocsge_coverage_status == 'COMPLETE_UNIFORM'

2023-12-05 15:49 UTC, Swannbm commented on project/models/project_base.py
> -    def is_artif(self):
Peut-être renommer is_ocsge_uniform et ajouter is_ocsge_complet, is_ocsge_partial, is_not_ocsge

2023-12-05 15:49 UTC, Swannbm commented on project/templates/project/partials/ocsge_status.html
> +        {% if project.ocsge_coverage_status == "PARTIAL" %}
ne pas utiliser de constante dans les templates

2023-12-05 15:49 UTC, Swannbm commented on project/templates/project/report_menu.html
> +                {% if project.ocsge_coverage_status != 'COMPLETE_UNIFORM'%}
Ne pas utiliser de constante dans les template

2023-12-07 12:54 UTC, merged