Ajout d'une commande pour supprimer Arcachon
MTES-MCT/sparte pull request #88
Opened 2023-11-28 13:44 UTC by alexisig

https://app.clickup.com/14136489

2023-11-29 19:57 UTC, Swannbm requested changes

2023-11-29 19:57 UTC, Swannbm commented on project/models/project_base.py
> +        TODO: remove the specific rule for Gironde
As-tu loggé une tâche dans clickup pour ne pas oublier ?

2023-11-30 07:39 UTC, alexisig commented on project/models/project_base.py
> +        TODO: remove the specific rule for Gironde
Le changement est déjà dans #82

2023-11-30 07:43 UTC, alexisig commented
J'ai fait un ticket pour ne pas oublier de supprimer la commande: https://app.clickup.com/t/869380wkh

2023-11-30 10:52 UTC, Swannbm approved these changes

2023-11-30 10:57 UTC, merged