Ajout des DROM-COM
MTES-MCT/sparte pull request #95
Opened 2023-12-07 10:46 UTC by alexisig

US: https://app.clickup.com/t/86933bzb3

- Ajout des données CEREMA des DROM-COM (à l'exception de Mayotte, car elles ne sont pas disponibles)
- Construction des limites administratives des DROM-COM à partir des données CEREMA
- Enregistrement des SRID des données source, et adaptation de toutes les fonctions qui calculent des surfaces.
- Ajout de la function de base de donnée `DynamicSRIDTransform`, ayant pour vocation de remplacer `Transform`: `DynamicSRIDTransform("mpoly", "srid_source")`
- Suppression de code inutilisé

----

Pour effectuer la migration, lancer la commande `load_drom_com`.

2024-01-18 17:33 UTC, Swannbm requested changes

2024-01-18 17:33 UTC, Swannbm commented on project/models/project_base.py
> +    LandException,
Les exceptions sont à stocker dans le fichier app/exceptions.py

2024-01-22 08:20 UTC, alexisig commented on project/migrations/0065_merge_20240109_0833.py
> +    operations = []
C'est un merge de deux migrations

2024-01-22 08:21 UTC, alexisig commented on project/models/project_base.py
> +    LandException,
C'est un import. Tu veux que je déplace `LandException` ?

2024-01-23 10:27 UTC, Swannbm commented on project/models/project_base.py
> +    LandException,
Oui, s'il te plaît. J'ai lu un article récemment sur le fait qu'il faut nettoyer à chaque fois que possible.

2024-01-24 15:26 UTC, merged